### ISSUE TITLE
Include facility to define version of standard in use

### ISSUE THREAD

**Issue by nickevansuk** [openactive/realtime-paged-data-exchange#17]
Different version for data and exchange standard? JSON-LD spec covers some of this?

**Comment by nickevansuk** [comment]
Need to provide a way of indicating the version of the spec used, however data consumers will need to be robust to variance in implementation, and no substantial breaking changes have been introduced yet

**Comment by nickevansuk** [comment]
@ldodds is this something we need before moving to final spec?

**Comment by ldodds** [comment]
We do need a version number. I'd suggest that we add one for the version of the paging spec and a means of declaring which standard + version a publisher is using to structure their `data` array.
