### ISSUE TITLE
'after' parameter should filter for greater-than-or-equal

### ISSUE THREAD

**Issue by johncowie** [openactive/realtime-paged-data-exchange#21]
Although opportunity IDs are must to be unique, it can be assumed that lastModified timestamps are not necessarily unique.  Therefore, when constructing the url for the next page with the last record of the previous, the 'after' query parameter should also return records that have the same lastModified timestamp as the last record on the preceding page.  This means that the text 

_from: the modified timestamp, after which results will be returned (if not specified will return from beginning of time)_

should become something like:

_from: the modified timestamp, after or at which results will be returned (if not specified will return from beginning of time)_

**Comment by nickevansuk** [comment]
Good spot, have corrected
