### ISSUE TITLE
Polling limitations

### ISSUE THREAD

**Issue by mattmcneeney** [openactive/realtime-paged-data-exchange#27]
What safeguards will be put in place to limit polling on endpoints? Will there be daily or weekly limits? Can endpoints dynamically request a "safe period" during which they should not be polled in case they are experiencing high load?

Re: [5.1 Polling](https://www.openactive.io/realtime-paged-data-exchange/#polling)

**Comment by nickevansuk** [comment]
Added HTTP status codes as a mechanism for requesting a "safe period"
