### ISSUE TITLE
Include something about the rationale for JSON

### ISSUE THREAD

**Issue by nickevansuk** [openactive/realtime-paged-data-exchange#6]
Make it clear why not XML

**Comment by nickevansuk** [comment]
Info available [here](https://github.com/openactive/realtime-paged-data-exchange/wiki/Design-Decisions), not sure if we need to include in spec though.

@ldodds ?

**Comment by ldodds** [comment]
I'm going to close this, I don't this we need to include a great deal of detail on those design decisions, especially if they're documented elsewhere.
