### ISSUE TITLE
Ambiguity of the term "record"

### ISSUE THREAD

**Issue by lukehesluke** [openactive/realtime-paged-data-exchange#64]
RE: Use of the term "records" in \#4.2. It's not completely clear what a "record" is. Is a record an:

1. Item? In this case, it would be uniquely and unambiguously identified by its ID
2. Item Update? In this case, it would be uniquely and unambiguously identified by two-tuple (ID, updated)

Clarification of this is vital for an unambiguous understanding of \#4.2 bullet point #2

**Comment by nickevansuk** [comment]
Great point, have clarified throughout
