### ISSUE TITLE
Increase lower limit of time to persist deleted items

### ISSUE THREAD

**Issue by lukehesluke** [openactive/realtime-paged-data-exchange#65]
The document specifies that deleted records must remain in the list for at least 48 hours (section #4.2)

It's not too surprising to imagine a syncing client which has a polling interval of 24 hours. If it's down just once, it may miss deleted sessions and persist them in its database indefinitely. How does 7 days (168 hours) sound as a replacement?

**Comment by nickevansuk** [comment]
Makes sense, have amended to 7 days
