### ISSUE TITLE
Modified timestamp should only be integer or string

### ISSUE THREAD

**Issue by lukehesluke** [openactive/realtime-paged-data-exchange#66]
RE "Note that the timestamp does not need to reflect actual time, as long as it providers a chronological ordering. An integer, string or **other representation** is sufficient" [emphasis mine] in section #4.3.1

In JSON the only other types are boolean, null, array or object. Don't think any of these would work to represent a date that can also be rendered in a URL. Suggest changing to just integer or string

**Comment by nickevansuk** [comment]
Good point, updated!
