### ISSUE TITLE
Mandating timezone awareness constraint

### ISSUE THREAD

**Issue by lukehesluke** [openactive/realtime-paged-data-exchange#68]
RE: section #4.5.3.1 bullet point #1

Everyone knows timezones are a b*llache. Might it be worth forcing a timezone awareness constraint at this early stage. i.e. "All dates MUST include timezone designator". This could then be followed by examples of datetimes that do and don't fit the criteria

**Comment by nickevansuk** [comment]
Good idea - this was already a requirement, but have made even more explicit
