### ISSUE TITLE
Loosen constraint on exponential backoff for polling

### ISSUE THREAD

**Issue by lukehesluke** [openactive/realtime-paged-data-exchange#70]
RE: section #5.1.2.2 -  "MUST poll [...] using exponential backoff"

Not sure about this being a fixed requirement. It may not be how a consumer would ideally be implemented e.g. a consumer might alter its polling rate based on time of day, expected updates, traffic, etc

**Comment by nickevansuk** [comment]
Good point - have replaced with "infrequent" recommendation.
