### ISSUE TITLE
More readable SQL query

### ISSUE THREAD

**Issue by lukehesluke** [openactive/realtime-paged-data-exchange#71]
RE: section #4.3.1.1

Given that this SQL query is so often misread, maybe it could be reformatted to this:

```
   WHERE (modified = @afterTimestamp
            AND id > @afterId)
      OR (modified > @afterTimestamp)
ORDER BY modified,
         id
```

(based on this style: http://www.sqlstyle.guide/)

**Comment by nickevansuk** [comment]
Great idea, have updated.
